package ru.net.network;

public enum TypeMessage {
    VERBAL_MESSAGE,
    SERVICE_MESSAGE_ADD_NAME,
    SERVICE_MESSAGE_UPDATE_LIST_USERS,
    SERVICE_MESSAGE_DEL_NAME,
    SERVICE_MESSAGE_CONNECT_ERROR
}
